"""LaTeX and Typst academic typesetting exporter."""

from __future__ import annotations

import re
from pathlib import Path


class AcademicTypesettingExporter:
    """Converts grounded markdown synthesis and bibliographies into LaTeX and Typst."""

    @classmethod
    def export_latex(
        cls,
        markdown_path: Path | str,
        bib_path: Path | str,
        output_path: Path | str,
    ) -> Path:
        """Convert markdown literature review to publication-ready LaTeX section."""
        md_file = Path(markdown_path)
        out_file = Path(output_path)
        out_file.parent.mkdir(parents=True, exist_ok=True)

        content = md_file.read_text(encoding="utf-8") if md_file.exists() else "# Literature Review\n\nNo synthesis found."

        # 1. Transform atomic citation tokens [DOC_ID#SEC#CHK] or [SCI-XXXXXX] to \cite{...}
        def cite_replacer(match: re.Match) -> str:
            raw_token = match.group(1)
            parts = raw_token.split("#")
            cite_key = parts[0].replace("-", "_")
            return f"\\cite{{{cite_key}}}"

        latex_body = re.sub(r"\[([A-Za-z0-9\-_]+#[A-Za-z0-9\-_]+#[A-Za-z0-9\-_]+)\]", cite_replacer, content)
        latex_body = re.sub(r"\[(SCI-\d+)\]", r"\\cite{\1}", latex_body)

        # 2. Transform Markdown headers to LaTeX sections
        latex_body = re.sub(r"^### (.*)$", r"\\subsubsection{\1}", latex_body, flags=re.MULTILINE)
        latex_body = re.sub(r"^## (.*)$", r"\\subsection{\1}", latex_body, flags=re.MULTILINE)
        latex_body = re.sub(r"^# (.*)$", r"\\section{\1}", latex_body, flags=re.MULTILINE)

        # 3. Transform bold/italic formatting
        latex_body = re.sub(r"\*\*(.*?)\*\*", r"\\textbf{\1}", latex_body)
        latex_body = re.sub(r"\*(.*?)\*", r"\\textit{\1}", latex_body)

        # 4. Wrap with LaTeX template
        bib_name = Path(bib_path).name if bib_path else "references.bib"
        latex_doc = (
            f"% Generated by Nexus Scholar Harness\n"
            f"\\documentclass{{article}}\n"
            f"\\usepackage[utf8]{{inputenc}}\n"
            f"\\usepackage{{amsmath,amssymb}}\n"
            f"\\usepackage{{cite}}\n"
            f"\\usepackage{{hyperref}}\n\n"
            f"\\begin{{document}}\n\n"
            f"{latex_body}\n\n"
            f"\\bibliographystyle{{IEEEtran}}\n"
            f"\\bibliography{{{bib_name.replace('.bib', '')}}}\n\n"
            f"\\end{{document}}\n"
        )

        out_file.write_text(latex_doc, encoding="utf-8")
        return out_file

    @classmethod
    def export_typst(
        cls,
        markdown_path: Path | str,
        bib_path: Path | str,
        output_path: Path | str,
    ) -> Path:
        """Convert markdown literature review to Typst format."""
        md_file = Path(markdown_path)
        out_file = Path(output_path)
        out_file.parent.mkdir(parents=True, exist_ok=True)

        content = md_file.read_text(encoding="utf-8") if md_file.exists() else "= Literature Review\n\nNo synthesis found."

        # 1. Transform atomic citation tokens to @citekey
        def typst_cite_replacer(match: re.Match) -> str:
            raw_token = match.group(1)
            parts = raw_token.split("#")
            cite_key = parts[0].replace("-", "_")
            return f"@{cite_key}"

        typst_body = re.sub(r"\[([A-Za-z0-9\-_]+#[A-Za-z0-9\-_]+#[A-Za-z0-9\-_]+)\]", typst_cite_replacer, content)
        typst_body = re.sub(r"\[(SCI-\d+)\]", r"@\1", typst_body)

        # 2. Transform Markdown headers to Typst headers (=, ==, ===)
        typst_body = re.sub(r"^### (.*)$", r"=== \1", typst_body, flags=re.MULTILINE)
        typst_body = re.sub(r"^## (.*)$", r"== \1", typst_body, flags=re.MULTILINE)
        typst_body = re.sub(r"^# (.*)$", r"= \1", typst_body, flags=re.MULTILINE)

        # 3. Wrap with Typst template
        bib_name = Path(bib_path).name if bib_path else "references.bib"
        typst_doc = (
            f"// Generated by Nexus Scholar Harness\n"
            f"#set page(paper: \"a4\", margin: (x: 2cm, y: 2.5cm))\n"
            f"#set text(font: \"Liberation Serif\", size: 11pt)\n\n"
            f"{typst_body}\n\n"
            f"#bibliography(\"{bib_name}\")\n"
        )

        out_file.write_text(typst_doc, encoding="utf-8")
        return out_file
