"""Nexus Scholar cross-kit contract v1 reference implementation."""

from .acceptance import (
    AcceptanceContext,
    AcceptanceIssue,
    AcceptanceResult,
    accept_artifact,
)
from .canonical import (
    canonical_fingerprint,
    canonical_json_bytes,
    corpus_snapshot_fingerprint,
    deterministic_id,
    normalize_doi,
)
from .chain import ArtifactChainIssue, ArtifactChainReport, validate_artifact_chain
from .identifiers import (
    ID_PREFIXES,
    IdentifierKind,
    identifier_registry,
    validate_identifier,
)
from .models import (
    CONTRACT_VERSION,
    ArtifactEnvelope,
    ArtifactReference,
    ClaimEvidenceLedger,
    ClaimItem,
    ContractError,
    CorpusSnapshotArtifact,
    DocumentContentStatus,
    DocumentManifestArtifact,
    EntailmentState,
    ErrorCode,
    EvidenceItem,
    LexicalSupport,
    MethodProvenance,
    OperationOutcome,
    OperationStatus,
    Producer,
    RetrievalState,
    RunManifest,
    ScreeningBatchArtifact,
    ScreeningDecision,
    ScreeningDecisionsArtifact,
    TrustState,
    VerificationAxes,
)
from .schema_catalog import load_schema, render_schema_files, schema_directory

__all__ = [
    "CONTRACT_VERSION",
    "ID_PREFIXES",
    "AcceptanceContext",
    "AcceptanceIssue",
    "AcceptanceResult",
    "ArtifactChainIssue",
    "ArtifactChainReport",
    "ArtifactEnvelope",
    "ArtifactReference",
    "ClaimEvidenceLedger",
    "ClaimItem",
    "ContractError",
    "CorpusSnapshotArtifact",
    "DocumentContentStatus",
    "DocumentManifestArtifact",
    "EntailmentState",
    "ErrorCode",
    "EvidenceItem",
    "IdentifierKind",
    "LexicalSupport",
    "MethodProvenance",
    "OperationOutcome",
    "OperationStatus",
    "Producer",
    "RetrievalState",
    "RunManifest",
    "ScreeningBatchArtifact",
    "ScreeningDecision",
    "ScreeningDecisionsArtifact",
    "TrustState",
    "VerificationAxes",
    "accept_artifact",
    "canonical_fingerprint",
    "canonical_json_bytes",
    "corpus_snapshot_fingerprint",
    "deterministic_id",
    "identifier_registry",
    "load_schema",
    "normalize_doi",
    "render_schema_files",
    "schema_directory",
    "validate_artifact_chain",
    "validate_identifier",
]
