"""Build D1 manuscript supplements:
1. synthesis/d1_references.md  - 94-corpus reference list keyed by SCI id (from literature/references.bib)
2. synthesis/rq1_metric_reporting.md - metric-reporting convention stats for RQ1 + corpus altitude/GSD stats
"""
import json, re
from pathlib import Path

BASE = Path(__file__).resolve().parent.parent
BIB = (BASE / "literature" / "references.bib").read_text(encoding="utf-8", errors="ignore")
RECORDS = json.loads((BASE / "literature/extraction/merged/records.json").read_text(encoding="utf-8"))

ENTRY_RE = re.compile(r"@(\w+)\{([^,]+),\s*(.*?)\n\}", re.S)
FIELD_RE = re.compile(r"(\w+)\s*=\s*[\{\"](.*?)[\}\"]", re.S)

def parse_bib():
    out = {}
    for kind, key, body in ENTRY_RE.findall(BIB):
        fields = {}
        for fk, fv in FIELD_RE.findall(body):
            fields[fk] = fv.strip()
        suf = key.rsplit("SCI", 1)
        sci = ("SCI-" + suf[1]) if len(suf) == 2 and suf[1].isdigit() else None
        out[key] = {"kind": kind, "fields": fields, "sci": sci}
    return out

def fmt_authors(author_str):
    parts = [p.strip() for p in author_str.split(" and ") if p.strip()]
    names = []
    for p in parts[:3]:
        if "," in p:
            fam, _, giv = p.partition(",")
            names.append(f"{fam.strip()}, {giv.strip().split()[0] if giv.strip() else ''}." if giv.strip() else fam.strip())
        else:
            bits = p.split()
            if len(bits) >= 2:
                names.append(f"{bits[-1]}, {bits[0][0]}.")
            else:
                names.append(p)
    if len(parts) > 3:
        names.append("et al.")
    return ", ".join(names)

def fmt_venue(f):
    return (f.get("journal") or f.get("booktitle") or f.get("publisher") or "n.p.").strip()

def fmt_year(f, kind):
    y = (f.get("year") or "").strip()
    if not y and kind == "unpublished":
        return "n.d."
    return y

ENT = parse_bib()
by_sci = {v["sci"]: v for v in ENT.values() if v["sci"]}

lines = ["# D1 references — 94-study audited corpus (keyed by workspace ID)\n"]
lines.append("Generated from `literature/references.bib` (150-entry bibliography) filtered to the "
             "94 clean-extraction corpus. Citation keys used in-text are the `SCI-xxxxxxx` IDs. "
             "APA-style rendered below; BibTeX source remains authoritative.\n")
lines.append("| # | Key | Reference | DOI/URL |")
lines.append("|---|---|---|---|")
miss = []
for i, r in enumerate(sorted(RECORDS, key=lambda x: x["workspace_id"]), 1):
    wid = r["workspace_id"]
    e = by_sci.get(wid)
    if not e:
        st = r.get("study", {})
        line = f"{st.get('title','?')} ({st.get('venue','?')}, {st.get('year','?')})"
        doi = ""
        miss.append(wid)
    else:
        f = e["fields"]
        ref = (fmt_authors(f.get("author", "")).rstrip(", ") +
               f" ({fmt_year(f, e['kind'])}) " + ". ".join(x for x in
               [f.get("title", "").rstrip(". "), fmt_venue(f).rstrip(". ")] if x).strip() + ".")
        ref = re.sub(r"\s+", " ", ref)
        ref = ref.replace("{", "").replace("}", "")
        ref = re.sub(r"\.{2,}", ".", ref)
        doi = f.get("doi") or f.get("url") or ""
        if doi and not doi.startswith("http"):
            doi = "https://doi.org/" + doi
    lines.append(f"| {i} | {wid} | {ref} | {doi} |")
lines.append(f"\n{len(RECORDS)} references rendered ({len(miss)} corpus entries missing from bib: {', '.join(miss) or 'none'}).\n")
(BASE / "synthesis" / "d1_references.md").write_text("\n".join(lines) + "\n", encoding="utf-8")

# ---- metric reporting supplement ----
import statistics
met_lines = ["# RQ1 metric reporting conventions (94-study corpus)\n"]
met_lines.append("Auto-generated by `scripts/build_d1_supplements.py`. Informs RQ1 §3.1/§3.3 and "
                 "Limitations (metric definition drift).\n")
metric_names = ("mIoU", "F1", "Dice", "PA", "mPA", "weed_F1", "crop_F1")
counts = {m: 0 for m in metric_names}
multi = 0
amb = 0
alt = 0
gsd = 0
alts = []
for r in RECORDS:
    m = r.get("segmentation", {}).get("metrics") or {}
    present = [k for k, v in m.items() if isinstance(v, dict) and v.get("value") is not None]
    for k in present:
        if k in counts:
            counts[k] += 1
    if len(present) > 1:
        multi += 1
    if any(isinstance(m.get(k), dict) and m[k].get("ambiguity") for k in m):
        amb += 1
    ds = (r.get("segmentation", {}).get("dataset") or {})
    if ds.get("flight_altitude_m"):
        alt += 1
        alts.append(ds["flight_altitude_m"])
    if ds.get("resolution_gsp_m"):
        gsd += 1
met_lines.append("| Metric | Studies reporting a numeric value | % of 94 |")
met_lines.append("|---|---:|---:|")
for k, v in counts.items():
    met_lines.append(f"| {k} | {v} | {100*v/94:.1f}% |")
met_lines.append(f"\n- Downstream of mIoU, F1 and Dice are the most common alternatives; PA/mPA and "
                 f"class-specific F1 (weed_F1/crop_F1) appear in a minority.")
met_lines.append(f"- Multi-metric reporting (≥2 numeric metrics): {multi}/94 ({100*multi/94:.0f}%).")
met_lines.append(f"- Rows where extraction flagged numeric ambiguity for at least one metric: {amb}/94.")
met_lines.append(f"- Dataset acquisition context reported: flight altitude in {alt}/94 (median "
                 f"{statistics.median(alts):.0f} m) and GSD in {gsd}/94 of dataset records.")
met_lines.append("\nInterpretation: reporting is single-metric-dominated (mIoU), so metric-definition "
                 "drift (per-class mean vs global mIoU, IoU vs Dice) cannot be reconciled cross-study; "
                 "the ambiguity flag indicates contested source readings that require human reconciliation before citation.")
(BASE / "synthesis" / "rq1_metric_reporting.md").write_text("\n".join(met_lines) + "\n", encoding="utf-8")
print("wrote d1_references.md + rq1_metric_reporting.md; bib total", len(ENT), "corpus-linked", len(by_sci), "missing-refs", len(miss))