"""Accuracy audit: cross-check top-20 anchor matrix rows against extracted fulltexts.

Anchor row = highest-confidence reported mIoU per distinct dataset (top 20).
Checks: (1) the mIoU number token appears in the extracted source,
(2) the extraction quote is found (normalized), (3) the model token is present.
Output: synthesis/rq1_anchor_audit.md — manuscript verification trail.
"""
import json, re
from pathlib import Path

BASE = Path(__file__).resolve().parent.parent
RECORDS = json.loads((BASE / "literature/extraction/merged/records.json").read_text(encoding="utf-8"))
EXTR = BASE / "extracted"

def norm(s):
    s = re.sub(r"[^0-9a-zA-Z]+", " ", str(s))
    return " ".join(s.lower().split())

def num_tokens(v):
    return re.findall(r"\d+(?:\.\d+)?", str(v))

def value_in_norm(txt_n, v):
    toks = num_tokens(v)
    if any(t in txt_n for t in toks):
        return True
    try:
        pct = f"{float(v)*100:.2f}"
        pct0 = f"{float(v)*100:.0f}"
    except (TypeError, ValueError):
        return False
    if pct in txt_n or pct0 in txt_n:
        return True
    vt = num_tokens(f"{float(v):.6f}")
    return any(t in txt_n for t in vt)

def model_in_norm(txt_n, model):
    toks = [t for t in norm(model).split() if len(t) >= 4]
    if not toks:
        return False
    return any(t in txt_n for t in toks)

anch = []
for r in RECORDS:
    seg = r.get("segmentation", {}) or {}
    m = (seg.get("metrics") or {}) if isinstance(seg.get("metrics"), dict) else {}
    mi = m.get("mIoU")
    if not isinstance(mi, dict):
        continue
    val, conf, q = mi.get("value"), mi.get("confidence"), (mi.get("quote") or "")
    if val is None or conf is None:
        continue
    anch.append((val, conf, r["workspace_id"], r["study"].get("extracted_md"), seg.get("best_model"), seg.get("dataset"), q))

anch.sort(key=lambda x: (-x[0], -x[1]))
seen = set()
top = []
for a in anch:
    if str(a[5]) not in seen:
        seen.add(str(a[5])); top.append(a)
    if len(top) >= 20:
        break

lines = []
lines.append("# RQ1 Anchor Accuracy Audit (top-20 per-dataset high-confidence mIoU rows)\n")
lines.append("Auto-generated by `scripts/rq1_anchor_audit.py`. Verification trail: claim value + model tokens matched against `extracted/*.md`.\n")
lines.append("| # | Study | claimed mIoU | conf | value-in-source | model-in-source | quote-found | verdict |")
lines.append("|---|---|---:|---:|:--:|:--:|:--:|---|")
n_fail = 0
for i, (val, conf, wid, md, model, ds, q) in enumerate(top, 1):
    f = EXTR / md
    if not f.exists():
        lines.append(f"| {i} | {wid} | {val} | {conf} | — | — | — | MISSING-FILE |")
        n_fail += 1
        continue
    txt = (f.read_text(encoding="utf-8", errors="ignore")).lower()
    txt_n = norm(txt)
    val_ok = value_in_norm(txt_n, val)
    model_ok = model_in_norm(txt_n, model)
    qn = norm(q)[:70]
    quote_ok = (len(qn) > 20 and qn in txt_n)
    verds = []
    if not val_ok: verds.append("VALUE")
    if not model_ok: verds.append("MODEL")
    if not quote_ok: verds.append("QUOTE")
    verdict = "OK" if not verds else "CHECK " + "/".join(verds)
    if verds: n_fail += 1
    lines.append(f"| {i} | {wid} | {val} | {conf} | {('Y' if val_ok else 'N')} | {('Y' if model_ok else 'N')} | {('Y' if quote_ok else 'N')} | {verdict} |")
lines.append(f"\nSummary: {len(top)} anchors, {len(top)-n_fail} fully grounded, {n_fail} flagged for manual check.\n")
lines.append("Rules: `value-in-source` = the mIoU numeric token occurs in the extracted text; `model-in-source` = normalized best_model token occurs; `quote-found` = extraction quote (normalized) occurs. VALUE/MODEL misses mean re-read the source; QUOTE miss alone may just be paraphrase — still verify.")
out = BASE / "synthesis" / "rq1_anchor_audit.md"
out.write_text("\n".join(lines) + "\n", encoding="utf-8")
print(f"wrote {out} ({len(lines)} lines) | anchors={len(top)} flagged={n_fail}")